DOMAIN = "tidbytassistant"

CONF_ID = "deviceid"
CONF_TOKEN = "token"
CONF_PORT = "port"
CONF_HOST = "host"
CONF_NAME = "name"
CONF_DEVICE = "device"
ATTR_CONTENT = "content"
ATTR_DEVICENANME = "devicename"
ATTR_CONT_TYPE = "contenttype"
ATTR_CUSTOM_CONT = "customcontent"
ATTR_CONTENT_ID = "contentid"
ATTR_TEXT_TYPE = "texttype"
ATTR_FONT = "font"