DOMAIN = "tidbytassistant"

CONF_ID = "deviceid"
CONF_TOKEN = "token"
CONF_PORT = "port"
CONF_HOST = "host"
CONF_NAME = "name"
CONF_DEVICE = "devices"
ATTR_CONTENT = "content"
ATTR_DEVICENANME = "devicename"