push:
  name: Push
  description: Push content to Tidbyt device.
  fields:
    content:
      name: Content
      description: The content you want displayed on the Tidbyt.
      required: false
      selector:
        select:
          options:
          - label: Coffee
            value: coffee
          - label: Dishwasher
            value: dishwasher
          - label: Doorbell
            value: doorbell
          - label: Dryer
            value: dryer
          - label: Filters
            value: filters
          - label: Fridge
            value: fridge
          - label: Garage Closed
            value: garageclosed
          - label: Garage Closing
            value: garageclosing
          - label: Garage Open
            value: garageopen
          - label: Trash
            value: trash
          - label: Trash Bins Out
            value: trashbinsout
          - label: Trash and Recycling
            value: trashrecycle
          - label: Trash and Recycling Bins Out
            value: trashrecbinsout
          - label: Washer
            value: washer
    customcontent:
      name: Custom Content
      description: 'Type the name of the custom content you want to display. Example:
        For custom you added ''example.star'' to /config/tidbyt then you would type
        ''example'' here.'
      required: false
      selector:
        text: null
    contenttype:
      name: Content Type
      description: Select between the built-in content or custom content. Custom content
        should be a .star file placed inside /config/tidbyt.
      required: true
      default: builtin
      selector:
        select:
          options:
          - label: Built-In
            value: builtin
          - label: Custom
            value: custom
    contentid:
      name: Content ID
      description: A unique name for your app. Alpha numeric characters only (A-Z,
        a-z or 0-9).
      required: false
      selector:
        text: null
    publishtype:
      name: Publish Type
      description: How you want content published. Background publishes without replacing
        the current app and Foreground will publish and also show you the app instantly.
      required: true
      default: foreground
      selector:
        select:
          options:
          - label: Foreground
            value: foreground
          - label: Background
            value: background
    language:
      name: Language
      description: Language to display built-in content.
      required: false
      default: en
      selector:
        select:
          options:
          - label: English
            value: en
          - label: German
            value: de
    arguments:
      name: Arguments
      description: 'Arguments you want to send to your .star app. This must be a key=value
        pair, separated by a semi-colon (;). Example: key=value;key2=value 2;key3=value3'
      required: false
      selector:
        text: null
    devicename:
      name: Device Name
      description: The Tidbyt device you want content to be displayed to.
      required: true
      selector:
        select:
          multiple: true
          options: &id001
          - label: Living Room
            value: Living Room
          - label: Office
            value: Office
          - label: Loft
            value: Loft
delete:
  name: Delete
  description: Delete an app from the rotation.
  fields:
    contentid:
      name: Content ID
      description: The Content ID you set when publishing your app. Specifying this
        adds the app to the rotation.
      required: true
      selector:
        text: null
    devicename:
      name: Device Name
      description: The Tidbyt device you want to delete the app from.
      required: true
      selector:
        select:
          multiple: true
          options: *id001
text:
  name: Text
  description: Push custom text to a Tidbyt device.
  fields:
    texttype:
      name: Text Type
      description: How you want the text displayed.
      default: regular
      required: true
      selector:
        select:
          options:
          - label: Regular
            value: regular
          - label: Scrolling
            value: scrolling
          - label: Title & Text
            value: title
    content:
      name: Content
      description: The text you want displayed.
      required: true
      selector:
        text: null
    font:
      name: Font
      description: Font for the text.
      required: true
      default: tb-8
      selector:
        select:
          options:
          - tb-8
          - Dina_r400-6
          - 5x8
          - 10x20
          - tom-thumb
          - CG-pixel-3x5-mono
          - CG-pixel-4x5-mono
          - 6x10
          - 6x10-rounded
          - 6x13
    color:
      name: Color
      description: Font color for the text.
      required: true
      default: '#fff'
      selector:
        select:
          options:
          - label: White
            value: '#fff'
          - label: Blue
            value: '#00f'
          - label: Red
            value: '#f00'
          - label: Green
            value: '#090'
          - label: Yellow
            value: '#ff0'
          - label: Cyan
            value: '#0ff'
          - label: Lime
            value: '#0f0'
    titlecontent:
      name: Title Content
      description: The text you want for the title.
      required: false
      selector:
        text: null
    titlefont:
      name: Title Font
      description: Font for the title.
      required: false
      default: 6x13
      selector:
        select:
          options:
          - tb-8
          - Dina_r400-6
          - 5x8
          - 10x20
          - tom-thumb
          - CG-pixel-3x5-mono
          - CG-pixel-4x5-mono
          - 6x10
          - 6x10-rounded
          - 6x13
    titlecolor:
      name: Title Color
      description: Font color for the title.
      required: false
      default: '#00f'
      selector:
        select:
          options:
          - label: White
            value: '#fff'
          - label: Blue
            value: '#00f'
          - label: Red
            value: '#f00'
          - label: Green
            value: '#090'
          - label: Yellow
            value: '#ff0'
          - label: Cyan
            value: '#0ff'
          - label: Lime
            value: '#0f0'
    contentid:
      name: Content ID
      description: The Content ID you set when publishing your app. Specifying this
        adds the app to the rotation.
      required: false
      selector:
        text: null
    publishtype:
      name: Publish Type
      description: How you want content published. Background publishes without replacing
        the current app and Foreground will publish and also show you the app instantly.
      required: true
      default: foreground
      selector:
        select:
          options:
          - label: Foreground
            value: foreground
          - label: Background
            value: background
    devicename:
      name: Device Name
      description: The Tidbyt device you want content to be displayed to.
      required: true
      selector:
        select:
          multiple: true
          options: *id001
